// Generated by sync-abis.mjs — do not edit by hand.
export const TournamentRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "launcher_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "annualChampionOf",
    "inputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAnnualFinalists",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getQuarterlyFinalists",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "quarter",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getWeeklyWinners",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAnnualFinalist",
    "inputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isQuarterlyFinalist",
    "inputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launcher",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markFiltered",
    "inputs": [
      {
        "name": "seasonId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "oracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "qualifiedFor",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "level",
        "type": "uint8",
        "internalType": "enum TournamentRegistry.CompetitionLevel"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quarterlyChampionOf",
    "inputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recordAnnualChampion",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "champion",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordAnnualFinalists",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordQuarterlyChampion",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "quarter",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "champion",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordQuarterlyFinalists",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "quarter",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "entrants",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordWeeklyWinner",
    "inputs": [
      {
        "name": "seasonId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "statusOf",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum TournamentRegistry.TokenStatus"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "weeklyWinnerCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "weeklyWinnerOf",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AnnualChampionRecorded",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "champion",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AnnualFinalistsRecorded",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "entrants",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "QuarterlyChampionRecorded",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "quarter",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "champion",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "QuarterlyFinalistsRecorded",
    "inputs": [
      {
        "name": "year",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "quarter",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "entrants",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenFiltered",
    "inputs": [
      {
        "name": "seasonId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WeeklyWinnerRecorded",
    "inputs": [
      {
        "name": "seasonId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "winner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyFinalized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyRecorded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadQuarter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyEntrants",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEligible",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOracle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRegisteredVault",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotTournamentVault",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongQuarterCount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroToken",
    "inputs": []
  }
] as const;
