/// Minimal ABI for the V4 PoolManager singleton.
///
/// Hand-written (not generated by `sync-abis.mjs`) because the V4 PoolManager is an
/// upstream Uniswap dependency, not a filter.fun contract — it lives in the
/// `v4-core` repo, not `packages/contracts/`. We only need its `Swap` event for
/// trade indexing; everything else (initialize, modifyLiquidity, etc.) is out of
/// scope here. If the V4 event signature ever changes, update both this file and
/// the matching handler in `src/V4PoolManager.ts`.
///
/// Signature (Uniswap V4 release):
///
///   event Swap(
///     PoolId indexed id,           // keccak256(abi.encode(PoolKey)) — bytes32
///     address indexed sender,      // typically the universal router or our hook
///     int128 amount0,              // signed; positive = token0 into pool, negative = out
///     int128 amount1,              // mirror of amount0 for token1
///     uint160 sqrtPriceX96,        // post-swap pool price
///     uint128 liquidity,           // pool's active in-range liquidity
///     int24 tick,                  // post-swap tick
///     uint24 fee                   // effective fee bps × 100
///   )
export const V4PoolManagerAbi = [
  {
    type: "event",
    name: "Swap",
    inputs: [
      {name: "id", type: "bytes32", indexed: true, internalType: "PoolId"},
      {name: "sender", type: "address", indexed: true, internalType: "address"},
      {name: "amount0", type: "int128", indexed: false, internalType: "int128"},
      {name: "amount1", type: "int128", indexed: false, internalType: "int128"},
      {name: "sqrtPriceX96", type: "uint160", indexed: false, internalType: "uint160"},
      {name: "liquidity", type: "uint128", indexed: false, internalType: "uint128"},
      {name: "tick", type: "int24", indexed: false, internalType: "int24"},
      {name: "fee", type: "uint24", indexed: false, internalType: "uint24"},
    ],
    anonymous: false,
  },
] as const;
