#!/usr/bin/env node
// Copies ABI arrays from `packages/contracts/out/<Contract>.sol/<Contract>.json` into `abis/`.
// Run after any contract change: `npm --workspace @filter-fun/indexer run abi:sync`.

import {readFileSync, writeFileSync, mkdirSync} from "node:fs";
import {join, dirname} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const contractsOut = join(root, "..", "contracts", "out");
const abiDir = join(root, "abis");
mkdirSync(abiDir, {recursive: true});

const targets = [
  "FilterLauncher",
  "FilterFactory",
  "FilterHook",
  "FilterLpLocker",
  "FilterToken",
  "SeasonVault",
  "BonusDistributor",
];

for (const name of targets) {
  const src = join(contractsOut, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(src, "utf8"));
  writeFileSync(join(abiDir, `${name}.json`), JSON.stringify(artifact.abi, null, 2));
  // Emit a const-asserted TS module so Ponder can infer event names/arg types.
  const tsBody =
    `// Generated by sync-abis.mjs — do not edit by hand.\n` +
    `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(abiDir, `${name}.ts`), tsBody);
  console.log(`✓ ${name}`);
}
